version: '3.8'
services:
  pg:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devecho

volumes:
  pgdata: null
